Implement bss
CanalTP/asgard pull request #91
Opened 2021-04-07 14:01 UTC by xlqian

2021-04-13 11:24 UTC, benoit-bst approved these changes
Fortunately there are tests !
It is tircky to handle

2021-04-13 15:41 UTC, pbench requested changes
Huge work ! And kudos for all the test cases.

2021-04-13 15:41 UTC, pbench commented on asgard/direct_path_response_builder.cpp
> +    }
Here, to ease future maintenance,  I suggest : 

- first identify the different cases you handle (no bss/bss with walking before and after/bss with walking after/bss with walking before/bss without walking
- make a different function for handling each case
- make specialized versions of `make_section` like `make_walking_section`, `make_rent_section` `make_return_section`, make_bike_section`

2021-04-13 15:41 UTC, pbench commented on asgard/mode_costing.cpp
> +    Options options = make_default_directions_options(args.mode);
Maybe add a comment here to explain why you need to ` * 3.6 `

2021-04-13 15:41 UTC, pbench commented on asgard/mode_costing.h
> +    float bss_return_penalty = 0;
Please add a comment here to specify :
- their units : seconds? minutes? euros? 
- their meaning/usage

2021-04-13 15:41 UTC, pbench commented on asgard/tests/direct_path_response_builder_test.cpp
> +    m->set_length(0.03);
What are these hardcoded values ? Why do you need them ?

2021-04-13 15:41 UTC, pbench commented on asgard/tests/handler_test.cpp
> +    // Destination is D
:smile:

2021-04-16 12:37 UTC, xlqian commented on asgard/direct_path_response_builder.cpp
> +        }
because the rent_cost/return_cost is included in the trip leg...

2021-04-16 12:44 UTC, xlqian commented on asgard/tests/direct_path_response_builder_test.cpp
> +    m->set_length(0.03);
because in the previous version, these values are computed from another source...

2021-04-16 12:45 UTC, xlqian commented on asgard/mode_costing.h
> +    float bss_return_penalty = 0;
Obviously, they're in euros :D

2021-04-19 09:43 UTC, xlqian commented on asgard/direct_path_response_builder.cpp
> +    if (bss_return_maneuver != directions_leg.maneuver().end()) {
bss_return_maneuver != directions_leg.maneuver().end() -1

2021-04-19 14:19 UTC, pbench approved these changes

2021-04-20 08:59 UTC, merged